[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "controller-skills-benchmark"
version = "0.1.0"
description = ""
dependencies = [
    "matplotlib>=3.7.5",
    "pygame>=2.6.0",
]
requires-python = ">=3.8"

[tool.hatch.build.targets.wheel]
packages = ["."]
